### ISSUE TITLE
add config option for different WAIT_INTERVAL

### ISSUE THREAD

**Issue by andy5995** [rawsonj/triviabot#66]
I suggest adding an option so the time between clues can be set differently than the time between questions. This would give admins some flexibility on what kind of "atmosphere" they'd like in their channels.

I'll write this code if you agree.

**Comment by andy5995** [comment]
In the code, I see that after a skipped question there is `self._lc.start(config.WAIT_INTERVAL)` but it's being ignored for some reason; the next question starts immediately.

**Comment by rawsonj** [comment]
I'm not opposed to having different delay values, but the primary purpose of the delay value is to make the bot safe from flood protection on IRC servers. You give it a value that's effectively the max rate at which the bot can post messages without being kicked from the server.

The reason why skipping starts immediately is on line 409 of trivia.py.

Basically, ?skip actually stops the LoopingCall timer and starts it again, causing an immediate flushing of the current state and executing _play_game immediately, which loads the next question and asks it. The timer is then set and the LoopingCall repeatedly calls _play_game on it's timer.

Reviewing this mechanism, I don't think it is possible using twisted to have different intervals for clues vs. questions, since it's all being driven with one LoopingCall object that has a single time.

**Comment by andy5995** [comment]
Ok, thanks for the explanation, Joe. I'll close it out.
