### ISSUE TITLE
Fix the stupid lambda some day.

### ISSUE THREAD

**Issue by VROS321** [rawsonj/triviabot#75]
Why am I getting this when trying to load trivia.py as a plugin in HexChat?:
 File "/home/lvr/Downloads/triviabot-master/trivia.py", line 450
     sorted_scores = sorted(self._scores.iteritems(), key=lambda (k, v): (v, k), reverse=True)
                                                                 ^
 SyntaxError: invalid syntax

Please help

**Comment by rawsonj** [comment]
It's the lambda. I remember I had an issue with it at one point but I couldn't remember a: What I did. b: What the actual problem was because iirc that's actually valid python.

I think it's equivalent to just having a function that switches it's inputs and returns a tuple, so maybe I'll try that out and do that just to not deal with this being a lambda.

**Comment by captnblood** [comment]
i have same problem

**Comment by rawsonj** [comment]
I'll fix this but like I said, it's not a problem and I think the syntax checker is wrong since the bot runs and does as expected.

**Comment by matheusfillipe** [comment]
There is no way this is python syntax:
`sorted_scores = sorted(self._scores.iteritems(), key=lambda (k, v): v, k, reverse=True)`

What python version is it? What is that even supposed to mean since if you added a comma after the lambda it mean another argument to the function which is a positional argument after a keyword argument.....

**Comment by matheusfillipe** [comment]
Maybe you mean: `  sorted_scores = sorted(self._scores.iteritems(), key=lambda k, v: (v, k), reverse=True)
`

**Comment by matheusfillipe** [comment]
Actually I figured out what you want is:
```sorted_scores = sorted(self._scores.iteritems(), key=lambda d: d[1], reverse=True```

The standings command work like that but is annoyingly slow.

**Comment by rawsonj** [comment]
lol, the moment I read that I was like "of course, silly me."

I wrote this in college to learn python, so of course a beginner would be worried about flipping the arguments instead of just sorting by the score.

And I don't have much time these days to work on this, but I'll fix that because its silly.
