### ISSUE TITLE
Answers must be given in the game channel

### ISSUE THREAD

**Issue by radien** [rawsonj/triviabot#79]
Answering a question in channel returns the response in the title.

**Comment by radien** [comment]
Playing around when i leave the trivia channel setting to #triviachannel it works fine but changing it to #trivia makes it spit out the error of not answering in the right channel.

**Comment by rawsonj** [comment]
I don't understand what your issue is.

The game is meant to be played in an established trivia channel, with a group of people everyone able to see what the others are doing.

The bot is written to only play the game in the game channel and not accept answers outside of the game channel. Its intended that commands can be given to the bot outside of the channel for administration purposes and that's roughly it.

**Comment by radien** [comment]
When I changed the channel the game is in.. (its #triviachannel in the config file) to be anything else, the bot would not acknowledge the new channel, as soon as I changed it back to #triviachannel it worked. but #trivia didn't nor anything else I tried..

Again.. This is when I change the game channel in the config to anything other then the default one you have it set. the bot doesn't work.

**Comment by rawsonj** [comment]
Try deleting the .pyc file after changing the config.

This could be the issue since I didn't feel the need to have a non-python
data serialization format for the config file.

If you confirm this is the case, I'll change the format to a json file
which will fix the problem.

**Comment by radien** [comment]
Okay, so after trying that and it not working I looked at everything over again just in case I missed something, in the config file the channel was #trivia but on the irc network the channel was #Trivia once I changed the config file to #Trivia it worked.

it's case sensitive.

**Comment by rawsonj** [comment]
Weird.
