### ISSUE TITLE
Always give three clues

### ISSUE THREAD

**Issue by za3k** [rawsonj/triviabot#81]
The current system is to give one clue for short words, and 3 clues for long words. Please give MAX(3, N-1) clues for all words, and just make it easier. One common problem is years: "1---" is a very bad clue for "birth of albert einstein".

**Comment by rawsonj** [comment]
Well, that's not really the algorithm.

From trivia.py:

   22     def give_clue(self):
   23     '''
   24     Returns the masked string after revealing a letter and saving the mask.
   25
   26     If an answer has only 1-2 characters in it, no clues are given.
   27
   28     If an answer has 3-4, 1 clue is given.
   29
   30     If an answer has 5-6, 2 clues are given.
   31     '''

I should have also stated "6 or more, 3 clues are given." This was decided upon basically from user feedback and testing. It's not perfect, but it works. My personal view is when you get a bad clue, such as in your example, you just got unlucky since the masking algorithm randomly chooses a position to unmask. Luck-of-the-draw is part of the game, so I'm not really inclined to change that part of the game.

It's also modelled after a BBS trivia program from the late 90's that had a very similar algorithm.

**Comment by za3k** [comment]
On 2021-02-24 20:49, Joe Rawson wrote:
> Well, that's not really the algorithm.
> 
> From trivia.py:
> 
> 22 def give_clue(self):
> 23 '''
> 24 Returns the masked string after revealing a letter and saving the
> mask.
> 25
> 26 If an answer has only 1-2 characters in it, no clues are given.
> 27
> 28 If an answer has 3-4, 1 clue is given.
> 29
> 30 If an answer has 5-6, 2 clues are given.
> 31 '''
> 
> I should have also stated "6 or more, 3 clues are given." This was
> decided upon basically from user feedback and testing. It's not
> perfect, but it works. My personal view is when you get a bad clue,
> such as in your example, you just got unlucky since the masking
> algorithm randomly chooses a position to unmask. Luck-of-the-draw is
> part of the game, so I'm not really inclined to change that part of
> the game.
> 
> It's also modelled after a BBS trivia program from the late 90's that
> had a very similar algorithm.

Sure. I've played this game for about 50-100 hours, and I'm telling you 
it's not really fun this way. If a bunch of other people have told you 
otherwise, ignore me.

**Comment by rawsonj** [comment]
Well, I've been running this game for the last 8 years and this was explicitly requested by the users of the server I run it on.

Feel free to fork it and do whatever you want to do, but this isn't a bug.
