### ISSUE TITLE
Question: Multiple data files?

### ISSUE THREAD

**Issue by za3k** [rawsonj/triviabot#83]
Is there any reason the question data is in multiple files? Is this to reduce RAM usage or something?

Was considering doing a Python3 port (to fix https://github.com/rawsonj/triviabot/issues/78) and saw some unrelated stuff that might be worth cleaning up.

**Comment by rawsonj** [comment]
Not really.

In the initial design of the program, I struggled with a simple, flexible way to store 300000 collected trivia questions.

A sqlite database was considered, but then users would have to know something about sqlite in order to edit questions.

So I decided on a stupid format for the files, but then I didn't want a monolithic file that was 300000 lines long, so we broke them up.

The algorithm for question selection picks a random file, then picks a random line from the selected file, which seemed like a good randomization.

But as I've grown up, I think a monolithic file would have been fine. I also think it would make it simpler to have different game modes, like 'sequential' (ie: start at the beginning of the file and walk each question to the end and repeat) or random, but I was learning python and programming at the time so it is what it is.

I've also been considering a python 3 port, just haven't found the time yet for this hobby program. Got a 3d printer and been messing with that for a bit. :)

**Comment by rawsonj** [comment]
Oh, and the algorithm I used is very sparing on memory. One should not load the whole file into memory, that's just a waste.

**Comment by za3k** [comment]
No, the algorithm you've used loads the entire file into memory (`lines = fd.read().splitlines()`), which is why I thought you might have split the file into many files.

**Comment by za3k** [comment]
(P.S. have fun with your 3d printer!)

**Comment by rawsonj** [comment]
lol, goes to show you how long it's been since I've read my own code.

Then yeah, ram usage would be a problem then. Wasn't my intention, but like I said, I was a student at the time.
